// Writes @mochart/editor's mochartConfigModel.generated.ts from the config-reference model. The
// output is git-ignored and regenerated by every editor build/test/typecheck, so it cannot go stale;
// the editor's MochartConfigModel type is pinned to the model shape below instead.
import { buildConfigReference } from './configReferenceModel';
import { getVersionString } from '../src/version';
import type { MochartConfigModel } from '../../mochart-editor/src/model';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'mochart-editor');
const outputPath = process.argv[2] ?? path.join(packageDir, 'src', 'mochartConfigModel.generated.ts');
const { model, integrityErrors } = buildConfigReference();

if (integrityErrors.length > 0) {
  throw new Error('Cannot generate editor model:\n' + integrityErrors.join('\n'));
}

// Stamped so the editor can detect a model built against a different core than the one installed.
const coreVersion = getVersionString();
// Typed against the editor's own model type so `npm run typecheck -w @mochart/core` fails when the
// two shapes drift; the generated file's cast could not catch that.
const editorModel: MochartConfigModel = { ...model, coreVersion };
const serialized = JSON.stringify(JSON.stringify(editorModel));
const source = [
  `// Generated by @mochart/core scripts/generateEditorModel.ts from @mochart/core ${coreVersion}. Do not edit.`,
  "import type { MochartConfigModel } from './model.js';",
  '',
  `const model = JSON.parse(${serialized}) as MochartConfigModel;`,
  '',
  'export default model;',
  ''
].join('\n');

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
// write-then-rename so a concurrent reader (another workspace's typecheck) never sees a partial file
const tempPath = outputPath + '.tmp';
fs.writeFileSync(tempPath, source);
fs.renameSync(tempPath, outputPath);
