import { getVersionString } from '@mochart/core';
import { describe, expect, it } from 'vitest';
import { mochartConfigEditorModel } from '../src';

describe('Mochart config editor model', () => {
  // Gate: the model is regenerated by generate/build/test, so a stamp that lags core means it was not.
  it('is stamped with the core version it was generated from', () => {
    expect(mochartConfigEditorModel.coreVersion).toBe(getVersionString());
  });

  it('contains top-level and section property metadata', () => {
    const series = mochartConfigEditorModel.sections.find(section => section.id === 'series');
    const axis = series?.properties.find(property => property.key === 'axis');

    expect(mochartConfigEditorModel.topLevel.some(property => property.key === 'series')).toBe(true);
    expect(series?.shape).toBe('array');
    expect(axis?.editor.types).toContain('string');
    expect(axis?.reference?.sections).toContain('valueAxes');
  });

  it('includes enum and range information derived from validators', () => {
    const chart = mochartConfigEditorModel.sections.find(section => section.id === 'chart');
    const type = chart?.properties.find(property => property.key === 'type');
    const pie = mochartConfigEditorModel.sections.find(section => section.id === 'pie');
    const radius = pie?.properties.find(property => property.key === 'innerRadiusFraction');

    expect(type?.editor.enum).toContain('pie');
    expect(radius?.editor.minimum).toBe(0);
    expect(radius?.editor.maximum).toBe(1);
  });

  it('describes automatic tooltip and legend icon sizing', () => {
    for (const sectionId of ['tooltip', 'legend']) {
      const section = mochartConfigEditorModel.sections.find(candidate => candidate.id === sectionId);
      const iconSize = section?.properties.find(property => property.key === 'icon')?.properties?.find(property => property.key === 'size');

      expect(iconSize?.editor.types).toEqual(expect.arrayContaining(['number', 'string']));
      expect(iconSize?.editor.enum).toContain('auto');
      expect(iconSize?.default?.text).toBe('"auto"');
    }
  });
});
