import { getVersionString } from '@mochart/core';
import { describe, expect, it } from 'vitest';
import { mochartConfigEditorModel } from '../src';

describe('Mochart config editor model', () => {
  // Gate: the model is regenerated by generate/build/test, so a stamp that lags core means it was not.
  it('is stamped with the core version it was generated from', () => {
    expect(mochartConfigEditorModel.coreVersion).toBe(getVersionString());
  });

  it('contains top-level and section property metadata', () => {
    const series = mochartConfigEditorModel.sections.find(section => section.id === 'series');
    const axis = series?.properties.find(property => property.key === 'axis');

    expect(mochartConfigEditorModel.topLevel.some(property => property.key === 'series')).toBe(true);
    expect(series?.shape).toBe('array');
    expect(axis?.editor.types).toContain('string');
    expect(axis?.reference?.sections).toContain('valueAxes');
  });

  it('includes enum and range information derived from validators', () => {
    const chart = mochartConfigEditorModel.sections.find(section => section.id === 'chart');
    const type = chart?.properties.find(property => property.key === 'type');
    const pie = mochartConfigEditorModel.sections.find(section => section.id === 'pie');
    const radius = pie?.properties.find(property => property.key === 'innerRadiusFraction');

    expect(type?.editor.enum).toContain('pie');
    expect(radius?.editor.minimum).toBe(0);
    expect(radius?.editor.maximum).toBe(1);
  });

  it('offers the literal forms of a bound whose number form depends on the axis scale', () => {
    const valueAxes = mochartConfigEditorModel.sections.find(section => section.id === 'valueAxes');
    const min = valueAxes?.properties.find(property => property.key === 'min');
    const softMin = valueAxes?.properties.find(property => property.key === 'softMin');
    const categoryAxis = mochartConfigEditorModel.sections.find(section => section.id === 'categoryAxis');
    const categoryMin = categoryAxis?.properties.find(property => property.key === 'min');

    expect(min?.editor.enum).toEqual(['auto']);
    expect(min?.editor.types).toEqual(expect.arrayContaining(['number', 'string']));
    expect(min?.editor.format).toBeUndefined();
    expect(softMin?.editor.enum).toEqual([null]);
    expect(categoryMin?.editor.format).toBeUndefined();
  });

  // positiveNumber had no editor type and a null-only log rule added 'any', so completions read "any | number | string"
  it('types the log-conditional value axis bounds and step members without any', () => {
    const valueAxes = mochartConfigEditorModel.sections.find(section => section.id === 'valueAxes');
    const property = (key: string) => valueAxes?.properties.find(candidate => candidate.key === key);
    const tickStep = property('tickStep')?.properties;

    expect(property('min')?.editor.types).toEqual(['number', 'string']);
    expect(property('softMin')?.editor.types).toEqual(['number']);
    expect(tickStep?.find(candidate => candidate.key === 'interval')?.editor.types).toEqual(['number']);
    expect(tickStep?.find(candidate => candidate.key === 'minorSteps')?.editor.types).toEqual(['number']);
    expect(property('thresholdStep')?.properties?.find(candidate => candidate.key === 'interval')?.editor.types).toEqual(['number']);
  });

  it('describes automatic tooltip and legend icon sizing', () => {
    for (const sectionId of ['tooltip', 'legend']) {
      const section = mochartConfigEditorModel.sections.find(candidate => candidate.id === sectionId);
      const iconSize = section?.properties.find(property => property.key === 'icon')?.properties?.find(property => property.key === 'size');

      expect(iconSize?.editor.types).toEqual(expect.arrayContaining(['number', 'string']));
      expect(iconSize?.editor.enum).toContain('auto');
      expect(iconSize?.default).toEqual({ kind: 'literal', text: '"auto"' });
    }
  });
});
